passwordAuthenticator:
  type: user
  config:
    entries:
      - username: user
        enabled: true
        passwordHash: $2a$12$vox7h99HV.gzbZGeBj69jeJVgkkP2nHTndG9USjp..00.WtIqvSpa # password is "password"
        attributes:
          roles: [user]
      - username: admin
        enabled: true
        passwordHash: $2a$12$vox7h99HV.gzbZGeBj69jeJVgkkP2nHTndG9USjp..00.WtIqvSpa # password is "password"
        attributes:
          roles: [admin]
      - username: customer
        enabled: true
        passwordHash: $2a$12$vox7h99HV.gzbZGeBj69jeJVgkkP2nHTndG9USjp..00.WtIqvSpa # password is "password"
        attributes:
          roles: [customer]
          entitlements: [product1]

# passwordAuthenticator:
#   type: unkey
#   config:
#     apiId: API_ID
#     rootKey: ROOT_KEY

accessTokenIssuer:
  type: jwt
  config:
    issuer: localhost:8080
    privateKeyFile: private_key.pem
    expiration: 15m

refreshTokenIssuer:
  type: jwt
  config:
    issuer: localhost:8080
    privateKeyFile: private_key.pem

# authorizer:
#   type: default
#   config:
#     allowAnonymous: false

authorizer:
  type: cerbos
  config:
    address: cerbos:3593
    options:
      plaintext: true
