version: "3.9"

services:
  portward:
    build: .
    command: [portward, --addr, 0.0.0.0:8080, --debug, --realm, localhost:8080, --config, /etc/portward/config.yaml]
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./config.yaml:/etc/portward/config.yaml
      - ./etc/portward/private_key.pem:/private_key.pem

  docker:
    image: registry:2.8.3
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./var/registries/docker:/var/lib/registry
      - ./etc/docker:/etc/docker/registry

  zot:
    image: ghcr.io/project-zot/zot-linux-amd64:v2.0.1
    ports:
      - 127.0.0.1:5001:5001
    volumes:
      - ./var/registries/zot:/var/lib/registry
      - ./etc/zot:/etc/zot

  cerbos:
    image: ghcr.io/cerbos/cerbos:0.33.0
    ports:
      - 127.0.0.1:3592:3592
      - 127.0.0.1:3593:3593
    volumes:
      - ./etc/cerbos/policies:/policies
