name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e:
    name: E2E test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Set up Nix
        uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Set up magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@8a218f9e264e9c3803c9a1ee1c30d8e4ab55be63 # v2

      - name: Prepare Nix shell
        run: nix develop --impure .#ci

      # Run this first to avoid permission issues with Docker
      - name: Download Alpine image
        run: nix develop --impure .#ci -c just download-alpine

      - name: Prepare configuration
        run: cp config.example.yaml config.yaml

      - name: Launch Docker Compose
        run: docker compose -f docker-compose.yaml up -d

      - name: Test
        run: nix develop --impure .#ci -c just test-all

      - name: Cleanup Docker Compose
        run: docker compose -f docker-compose.yaml down -v
        if: always()

  dev:
    name: Developer environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Set up Nix
        uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Set up magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@8a218f9e264e9c3803c9a1ee1c30d8e4ab55be63 # v2

      - name: Check
        run: nix flake check --impure

      - name: Dev shell
        run: nix develop --impure
